DROP TABLE IF EXISTS `2dof_sessions`;
DROP TABLE IF EXISTS `2dof_disks`;
DROP TABLE IF EXISTS `2dof_runs`;

CREATE TABLE `2dof_sessions` (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    session_id VARCHAR(5) NOT NULL UNIQUE,
    created_by BIGINT UNSIGNED NOT NULL REFERENCES wpf_users(ID) ON DELETE CASCADE,
    ts_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `2dof_disks` (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    disk_code VARCHAR(4) NOT NULL UNIQUE,
    path JSON NOT NULL,
    ts_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `2dof_runs` (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user BIGINT UNSIGNED NOT NULL REFERENCES wpf_users(ID) ON DELETE CASCADE,
    session_ref BIGINT UNSIGNED NOT NULL REFERENCES 2dof_sessions(id) ON DELETE CASCADE,
    disk_ref BIGINT UNSIGNED NOT NULL REFERENCES 2dof_disks(id) ON DELETE CASCADE,
    eval DECIMAL(5,2) NOT NULL,
    ts_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);